namespace GeolocationComponent
{
	[default_interface]
	runtimeclass GeolocationService
	{
		GeolocationService();
		Windows.Foundation.IAsyncOperation<double> GetLatitude();
		Windows.Foundation.IAsyncOperation<double> GetLongitude();
	}
}
